debug: false
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 5
    initialization-mode: always
    schema:
    - classpath:scripts/schema.sql
    data:
    - classpath:scripts/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    topic:
      name: "notification-test"